language: c

os:
  - linux

compiler:
  - gcc

cache:
  directories:
    - $HOME/torch

sudo: true

branches:
  only:
    - master

env:
  - TORCH_LUA_VERSION="LUAJIT21"
  - TORCH_LUA_VERSION="LUA52"

before_install:
  - set -evx
  - source travis/install_torch.inc.sh

script:
  - which th luarocks || exit 1;
  - th test/util/math.lua
  - th test/util/table.lua

notifications:
  email:
    on_success: change
    on_failure: always
